filters:
  # - label: feat
  #   regexs:
  #     - /\bfeat\b/
  #     - /feature/i
  #   events: [issues, pull_request]
  #   targets: [title, comment]
  # - label: bug
  #   regexs:
  #     - /fix|bug/
  #   targets: [title]
  # - label: documentation
  #   regexs:
  #     - /docs/
  #   events: [pull_request]
  # - label: chore
  #   regexs:
  #     - /\bchore(\(.*\))?:/i
  - label: 1조
    regexs:
      - /^.*(박지연|이미경|이충현|나원지|서동균|김민지).*$/
  - label: 3조
    regexs:
      - /^.*(모소현|이샘미|이효주).*$/
  - label: 4조
    regexs:
      - /^.*(김초원|심승혁|형예은).*$/
  - label: 5조
    regexs:
      - /^.*(정수진|양혜원|여지영).*$/
  - label: 6조
    regexs:
      - /^.*(오현석|안수빈|최서현).*$/
  - label: 7조
    regexs:
      - /^.*(최현우|나지은|최규연).*$/
  - label: 8조
    regexs:
      - /^.*(모신영|박지영|김혜성).*$/
  - label: 9조
    regexs:
      - /^.*(유시온|박동현|서범석).*$/
  - label: 10조
    regexs:
      - /^.*(신정규|서준환|유진리).*$/
  - label: 11조
    regexs:
      - /^.*(김희주|신승준|이한결).*$/
  - label: 12조
    regexs:
      - /^.*(안주홍|신명희|전창기).*$/
  - label: 13조
    regexs:
      - /^.*(이예빈|김자연|박혜미).*$/
  - label: 14조
    regexs:
      - /^.*(오윤석|김지원|조수빈).*$/